#!/usr/bin/env bash

# stop script when a command returns with non-zero
set -e

POCAML="./pocamlc"
PFLAGS=""
COMPILE_ONLY=0
FROM_STDIN=0
CLEAN=0

c_lib="_pml_build/pml_builtins.a"

Usage()
{
  echo
  echo "usage:	pocaml [options] [<path_to_pml_file>...]"
  echo
  echo "-c	Only compile .pml files"
  echo "-h	Display this help"
  echo "-x	Clean and remove all build artifacts before compilation"
  echo

  exit 1
}

SetFlags()
{
    if [ $COMPILE_ONLY -eq 1 ]
    then
	PFLAGS="-c"
	return
    fi

    PFLAGS="$PFLAGS -r"

    if [ -f $c_lib ] && [ $CLEAN -eq 0 ]
    then
	# use existing C static lib
	PFLAGS="$PFLAGS -bs"
    else
	PFLAGS="$PFLAGS -c"
    fi

    if [ $FROM_STDIN -eq 0 ]
    then
	PFLAGS="$PFLAGS -f"
    fi
}

[ $# -eq 0 ] && Usage

while getopts chx opt; do
    case $opt in
	c)
	    COMPILE_ONLY=1
	    ;;
	x)
	    CLEAN=1
	    ;;
	*)
	    Usage
	    ;;
    esac
done

shift $(($OPTIND - 1))

if [ $# -eq 0 ]
then
    FROM_STDIN=1
fi

SetFlags

for file in $@
do
    $POCAML $PFLAGS $file
done

if [ $FROM_STDIN -ne 0 ]
then
    $POCAML $PFLAGS
fi

exit 0
