let builtin_names =
  [
    "_not";
    "_add";
    "_minus";
    "_times";
    "_divide";
    "_less_than";
    "_less_equal";
    "_greater_than";
    "_greater_equal";
    "_equal";
    "_not_equal";
    "_or";
    "_and";
    "_cons";
    "_seq";
    "string_of_int";
    "string_of_bool";
    "string_of_char";
    "print_string"
  ]
